### ISSUE TITLE
Logger - Learning Tables View showing incorrect table axis values

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#67]
When an ECU definition contains table attributes and inherits other table attributes from another definition the initial attribute values are overwriten by the inherited values.
Fix addAttributesAsMap() in class com.romraider.logger.ecu.definition.xml.EcuTableDefinitionHandler to skip a Map value update if the Key is already present.

**Comment by dschultzca** [comment]
Fixed in commit 2d118351f9bd7726437e46e77e20ed5c99acda79

**Comment by bluegizmo83** [comment]
I know this issue was closed in 2017, but I'm having the same issue still in 2024... Learning View tables for AFR and Timing all show zeros for the axis.
